<br>
<p>Professional hire for classic, vintage, and contemporary costumes./p> 
<p></p>Use for shop displays, TV, film, theater or promotional events, parties, weddings, graduations, our wide range will meet all your needs./p>
<p>All costumes are categorised by period, size, comfort and look.</p>
<p>Book an appointment to visit our costume store, our professional and knowledgeable team is on hand with expert fitting and styling advice.</p>